deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: 'us-northeast-2'
  app: 'moonda-server'
  env: 'moonda-server-dev'
  bucket_name: 'moonda-server-dev'
